--
-- PostgreSQL database dump
--

-- Dumped from database version 10.5
-- Dumped by pg_dump version 10.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


--
-- Name: set_hash(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_hash() RETURNS trigger
    LANGUAGE plpgsql IMMUTABLE STRICT
    AS $$
  BEGIN
    NEW.hash := MD5(NEW.id::VARCHAR || NEW.url || COALESCE(NEW.referer, '') || NEW.created_at::VARCHAR);
    RETURN NEW;
  END;
  $$;


SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    filename text NOT NULL
);


--
-- Name: visits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.visits (
    id integer NOT NULL,
    url text NOT NULL,
    referer text,
    created_at timestamp without time zone NOT NULL,
    hash character varying(32) NOT NULL
);


--
-- Name: visits_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.visits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.visits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);


--
-- Name: visits visits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.visits
    ADD CONSTRAINT visits_pkey PRIMARY KEY (id);


--
-- Name: visits_date_url; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX visits_date_url ON public.visits USING btree (((date_trunc('day'::text, created_at))::date), url);


--
-- Name: visits trg_set_hash; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_set_hash BEFORE INSERT ON public.visits FOR EACH ROW EXECUTE PROCEDURE public.set_hash();


--
-- PostgreSQL database dump complete
--

SET search_path TO "$user", public;
INSERT INTO "schema_migrations" ("filename") VALUES ('20180828010023_create_visits.rb');